### PR TITLE
feat(log4j): add custom template support

### PR DESCRIPTION
**Pull request by finalhow**
Update code to allow customized templates for log4j2 configurations.

### CODE REVIEW

**Comment by minorOffense** [comment]
Instead just add a variable with the path to a template. Then eps or whoever can specify a path to another template they control. 

If you want to add other example templates that’s fine too. But you don’t need the struct or enum. Just have a variable called log4j_template and set the default value to the current path.

**Review by minorOffense — CHANGES_REQUESTED** [review]
Add the extra templates but allow any path so they can use their own template from their own puppet code. Just set the default to the current template location.

**Comment by finalhow** [comment]
> Add the extra templates but allow any path so they can use their own template from their own puppet code. Just set the default to the current template location.

Ok, sounds good.. can this kind of path support both URLs and file locations or ...?

**Comment by minorOffense** [comment]
No it would just be a path to an epp template in a module somewhere.

**Pull request closed without merging**
